define([], function() {
  return {
    MODEL_EVENTS: 'change sync',
    COLLECTION_EVENTS: 'add change remove reset fetch',

    ACCESS_POLICY_PUBLIC: 'public',
    ACCESS_POLICY_PRIVATE: 'private',

    APP_PRIMARY_LAYER: 'APP_PRIMARY_LAYER',
    APP_SECONDARY_LAYER: 'APP_SECONDARY_LAYER',
    APP_TRACK_ROUTE: 'APP_TRACK_ROUTE',

    ERROR_ACCESS_UNAUTHORIZED: 'Unauthorized',
    ERROR_ACCESS_OVERAUTHORIZED: 'Overauthorized',
    ERROR_NOT_FOUND: 'NOT_FOUND',

    ACCOUNT_REQUIRED: 'ACCOUNT_REQUIRED',
    COURSE_REQUIRED: 'COURSE_REQUIRED',

    SESSION_CREATE: 'SESSION_CREATE',
    SESSION_DESTROY: 'SESSION_DESTROY',

    USER_CREATE: 'USER_CREATE',
    USER_LOAD: 'USER_LOAD',
    USER_MAX_PER_PAGE: 50,
    USER_MASS_ENROLL: 'USER_MASS_ENROLL',
    USER_MIN_ENROLL: 1,
    USER_MAX_ENROLL: 5000,
    USER_STUDENT_ENROLLMENT: 'StudentEnrollment',

    // Status codes for mass user enrollment
    USER_ENROLLMENT_COUNT_TOO_LOW: 'USER_ENROLLMENT_COUNT_TOO_LOW',
    USER_ENROLLMENT_COUNT_TOO_HIGH: 'USER_ENROLLMENT_COUNT_TOO_HIGH',

    USER_REGISTERING: 'USER_REGISTERING',
    USER_ENROLLING: 'USER_ENROLLING',
    USER_LOADING: 'USER_LOADING',

    ACCOUNT_ACTIVATE: 'ACCOUNT_ACTIVATE',
    COURSE_ACTIVATE: 'COURSE_ACTIVATE',

    QUIZ_ACTIVATE: 'QUIZ_ACTIVATE',

    RECIPE_ENROLL_STUDENTS: '/recipes/enroll_students',
    RECIPE_ENROLL_STUDENTS_PROGRESS: '/recipes/enroll_students/progress',
    RECIPE_LOAD_STUDENTS: '/recipes/load_students',
    RECIPE_TAKE_QUIZ: '/recipes/take_quiz',

    ROUTE_GO_TO_QUIZ: 'ROUTE_GO_TO_QUIZ',

    QUIZ_TAKING_SET: 'QUIZ_TAKING_SET',
    QUIZ_TAKING_SET_RESPONSE_RATIO: 'QUIZ_TAKING_SET_RESPONSE_RATIO',
    QUIZ_TAKING_SET_RESPONSE_COUNT: 'QUIZ_TAKING_SET_RESPONSE_COUNT',
    QUIZ_TAKING_TAKE: 'QUIZ_TAKING_TAKE',
    QUIZ_TAKING_ADD_ANSWER: 'QUIZ_TAKING_ADD_ANSWER',
    QUIZ_TAKING_ADD_ANSWER_TO_VARIANT: 'QUIZ_TAKING_ADD_ANSWER_TO_VARIANT',
    QUIZ_TAKING_ADD_VARIANT: 'QUIZ_TAKING_ADD_VARIANT',
    QUIZ_TAKING_REMOVE_VARIANT: 'QUIZ_TAKING_REMOVE_VARIANT',

    QUIZ_TAKING_RESPONSE_GENERATION_FAILED: 'QUIZ_TAKING_RESPONSE_GENERATION_FAILED',

    // Preparing the submission.
    QUIZ_TAKING_PREPARING: 'QUIZ_TAKING_PREPARING',
    QUIZ_TAKING_PREPARATION_FAILED: 'QUIZ_TAKING_PREPARATION_FAILED',

    // Answering it using the QuizTaker.
    QUIZ_TAKING_ANSWERING: 'QUIZ_TAKING_ANSWERING',
    QUIZ_TAKING_ANSWERING_FAILED: 'QUIZ_TAKING_ANSWERING_FAILED',

    // Turning it in.
    QUIZ_TAKING_TURNING_IN: 'QUIZ_TAKING_TURNING_IN',
    QUIZ_TAKING_TURNING_IN_FAILED: 'QUIZ_TAKING_TURNING_IN_FAILED',

    QUIZ_TAKING_LOADING_STUDENTS: 'quizTakingStatusLoadingStudents',

    FREE_FORM_INPUT_QUESTIONS: [
      'fill_in_multiple_blanks_question',
      'essay_question',
      'short_answer_question',
      'numerical_question',
      'calculated_question',
    ],

    QUESTIONS_WITH_ANSWER_SETS: [
      'fill_in_multiple_blanks_question',
      'multiple_dropdowns_question',
      // 'matching_question',
    ],

    QUESTIONS_WITH_VARIANTS: [
      'multiple_answers_question',
      'matching_question',
    ],

    MANUALLY_GRADED_QUESTIONS: [
      'essay_question',
      'file_upload_question'
    ],

    QUESTION_MISSING_ANSWER: 'none',
    QUESTION_MISSING_ANSWER_TEXT: 'No Answer',
    QUESTION_UNKNOWN_ANSWER: 'other',
    QUESTION_UNKNOWN_ANSWER_TEXT: 'Something Else',
    QUESTION_NUMERICAL_EXACT_ANSWER: 'exact_answer',
    QUESTION_NUMERICAL_RANGE_ANSWER: 'range_answer',

    DEFAULT_ID_PREFIX: 'quizard',
    STUDENT_EMAIL_DOMAIN: 'quizard.com',
    STUDENT_PASSWORD: 'quizard_student_password',

    OPERATION_ACTIVE: 'OPERATION_ACTIVE',
    OPERATION_ABORT: 'OPERATION_ABORT',
    OPERATION_ABORTED: 'OPERATION_ABORTED',
    OPERATION_FAILED: 'OPERATION_FAILED',
    OPERATION_COMPLETE: 'OPERATION_COMPLETE',
    OPERATION_BOX_MINIMIZE: 'OPERATION_BOX_MINIMIZE',
    OPERATION_BOX_RESTORE: 'OPERATION_BOX_RESTORE',
  };
});