define([], function() {
  return {
    MODEL_EVENTS: 'change sync',
    COLLECTION_EVENTS: 'add change remove reset fetch',

    ACCESS_POLICY_PUBLIC: 1,
    ACCESS_POLICY_PRIVATE: 2,

    APP_PRIMARY_LAYER: 200,
    APP_SECONDARY_LAYER: 201,
    APP_TRACK_ROUTE: 202,

    // Use strings for i18n
    ERROR_ACCESS_UNAUTHORIZED: 'ACCESS_UNAUTHORIZED',
    ERROR_ACCESS_OVERAUTHORIZED: 'ACCESS_OVERAUTHORIZED',
    ERROR_NOT_FOUND: 'NOT_FOUND',

    SESSION_CREATE: 'SESSION_CREATE',
    SESSION_DESTROY: 'SESSION_DESTROY',

    NAVIGATION_USERS: 300,

    USER_LOAD_ALL: 400,

    ACCOUNT_ACTIVATE: 500,
  };
});