define([], function() {
  return {
    MODEL_EVENTS: 'change sync',
    COLLECTION_EVENTS: 'add change remove reset fetch',

    ACCESS_POLICY_PUBLIC: 'public',
    ACCESS_POLICY_PRIVATE: 'private',

    APP_PRIMARY_LAYER: 'APP_PRIMARY_LAYER',
    APP_SECONDARY_LAYER: 'APP_SECONDARY_LAYER',
    APP_TRACK_ROUTE: 'APP_TRACK_ROUTE',

    ERROR_ACCESS_UNAUTHORIZED: 'Unauthorized',
    ERROR_ACCESS_OVERAUTHORIZED: 'Overauthorized',
    // Use strings for i18n
    ERROR_NOT_FOUND: 'NOT_FOUND',

    SESSION_CREATE: 'SESSION_CREATE',
    SESSION_DESTROY: 'SESSION_DESTROY',

    USER_CREATE: 'USER_CREATE',
    USER_LOAD_ALL: 'USER_LOAD_ALL',

    ACCOUNT_ACTIVATE: 'ACCOUNT_ACTIVATE',

    PUBLIC_LAYOUT_NAME: 'guest',
    PRIVATE_LAYOUT_NAME: 'member',

    DEFAULT_PUBLIC_ROUTE: '/welcome',
    DEFAULT_PRIVATE_ROUTE: '/app'
  };
});